<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  
  <ItemGroup>
    <Reference Include="CurryEngine.Runtime">
	  <HintPath>..\x64\Debug\CurryEngine.API.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(OutDir)Assembly-CSharp.dll" DestinationFolder="$(MSBuildProjectDirectory)\..\x64\Debug\" />
  </Target>
</Project>
