<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	<AssemblyName>CurryEngine.API</AssemblyName>
	<RootNamespace>CurryEngine</RootNamespace>
	<Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

	<ItemGroup>
		<Compile Include="$(SolutionDir)Generated\CSharp\**\*.g.cs" />
	</ItemGroup>
	
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(OutDir)CurryEngine.API.dll" DestinationFolder="$(MSBuildProjectDirectory)\..\x64\$(Configuration)\" />
	</Target>
</Project>
