#include "CSharpGenerater.h"
#include "Parser.h"

#include <fstream>
#include <iostream>
#include <sstream>
#include <filesystem>

#include "../../External/tinygltf-release/json.hpp"

// ============================================================
//  コンストラクタ / LoadTypeMap
// ============================================================

CSharpGenerater::CSharpGenerater(
    const std::string& outputDir,
    const std::string& typeMapPath,
    const std::string& nmNamespace,
    const std::string& csNamespace)
    : outputDirectory(outputDir)
    , nmNamespace(nmNamespace)
    , csNamespace(csNamespace)
    , dllConstant(nmNamespace + ".NativeMethods.Dll")
{
    if (!std::filesystem::exists(outputDirectory))
        std::filesystem::create_directories(outputDirectory);

    LoadTypeMap(typeMapPath);
}

void CSharpGenerater::LoadTypeMap(const std::string& path)
{
    std::ifstream ifs(path);
    if (!ifs.is_open())
    {
        std::cout << "Warning: type_map.json not found at " << path << ". Using empty map.\n";
        return;
    }

    nlohmann::json j;
    ifs >> j;

    for (auto& [cppType, entry] : j.items())
    {
        TypeMapping m;
        m.csType = entry.value("csType", cppType);

        std::string src = entry.value("source", "primitive");
        if (src == "existing")  m.source = TypeSource::Existing;
        else if (src == "generate")  m.source = TypeSource::Generate;
        else                         m.source = TypeSource::Primitive;

        m.marshalAttr = entry.value("marshalAttr", "");
        typeMap[cppType] = m;
    }

    std::cout << "Loaded " << typeMap.size() << " type mappings.\n";
}

// ============================================================
//  型解決ヘルパー
// ============================================================

std::string CSharpGenerater::ResolveCsType(const std::string& cppType) const
{
    auto it = typeMap.find(cppType);
    if (it != typeMap.end()) return it->second.csType;

    std::cout << "Warning: Unknown type '" << cppType << "'. Using as-is.\n";
    return cppType;
}

std::string CSharpGenerater::ResolveMarshalAttr(const std::string& cppType) const
{
    auto it = typeMap.find(cppType);
    if (it != typeMap.end()) return it->second.marshalAttr;
    return "";
}

// ============================================================
//  Generate（エントリポイント）
// ============================================================

void CSharpGenerater::Generate(const std::vector<FileInfo>& files)
{
    for (const auto& file : files)
    {
        for (const auto& cls : file.classes)
        {
            if (!cls.reflect) continue;
            GenerateNativeMethods(cls);
            GenerateWrapper(cls);
        }
        for (const auto& e : file.enums)
            GenerateEnum(e);
        for (const auto& s : file.structs)
            GenerateStruct(s);
    }
}

// ============================================================
//  GenerateNativeMethods → NativeMethods.Xxx.g.cs
//
//  namespace CurryEngine.Interop;
//  internal static partial class NativeMethods
//  {
//      [LibraryImport(Dll)] internal static partial float Rigidbody_GetMass(ulong ownerId);
//      ...
//  }
// ============================================================

void CSharpGenerater::GenerateNativeMethods(const ClassInfo& info)
{
    std::string outPath = outputDirectory + "/NativeMethods." + info.name + ".g.cs";
    std::ofstream ofs(outPath);
    if (!ofs.is_open()) throw std::runtime_error("Cannot open: " + outPath);

    ofs << "// <auto-generated/>\n";
    ofs << "using System.Runtime.InteropServices;\n";
    ofs << "using " << csNamespace << ";\n\n";
    ofs << "namespace " << nmNamespace << ";\n";
    ofs << "internal static partial class NativeMethods\n{\n";

    // フィールドごとに Get/Set の LibraryImport を生成
    for (const auto& field : info.fields)
        ofs << BuildFieldImportLines(info.name, field, 1);

    // メソッドの LibraryImport を生成
    for (const auto& method : info.methods)
        ofs << BuildLibraryImportLine(info.name, method, 1);

    ofs << "}\n";
    std::cout << "Generated: " << outPath << "\n";
}

// ============================================================
//  GenerateWrapper → XxxComponent.g.cs
//
//  namespace CurryEngine;
//  public sealed partial class Rigidbody : Component
//  {
//      public float mass { get => NativeMethods.Rigidbody_GetMass(ownerId); ... }
//      ...
//  }
// ============================================================

void CSharpGenerater::GenerateWrapper(const ClassInfo& info)
{
    std::string outPath = outputDirectory + "/" + info.name + ".g.cs";
    std::ofstream ofs(outPath);
    if (!ofs.is_open()) throw std::runtime_error("Cannot open: " + outPath);

    // 基底クラスの決定（bases が空なら Component にフォールバック）
    std::string baseClass = info.bases.empty() ? "Component" : info.bases[0];

    ofs << "// <auto-generated/>\n";
    ofs << "using " << nmNamespace << ";\n\n";
    ofs << "namespace " << csNamespace << ";\n";
    ofs << "public sealed partial class " << info.name << " : " << baseClass << "\n{\n";

    // プロパティ
    for (const auto& field : info.fields)
        ofs << BuildPropertyImpl(info.name, field, 1);

    // メソッド
    for (const auto& method : info.methods)
        ofs << BuildMethodImpl(info.name, method, 1);

    ofs << "}\n";
    std::cout << "Generated: " << outPath << "\n";
}

// ============================================================
//  GenerateEnum → XxxEnum.g.cs
// ============================================================

void CSharpGenerater::GenerateEnum(const EnumInfo& info)
{
    std::string outPath = outputDirectory + "/" + info.name + ".g.cs";
    std::ofstream ofs(outPath);
    if (!ofs.is_open()) throw std::runtime_error("Cannot open: " + outPath);

    // underlyingType の C# マッピング
    std::string csUnderlying = ResolveCsType(info.underlyingType);

    ofs << "// <auto-generated/>\n";
    ofs << "namespace " << csNamespace << ";\n";
    ofs << "public enum " << info.name << " : " << csUnderlying << "\n{\n";

    for (size_t i = 0; i < info.values.size(); i++)
    {
        const auto& v = info.values[i];
        ofs << Indent(1) << v.name << " = " << v.value;
        if (i < info.values.size() - 1) ofs << ",";
        ofs << "\n";
    }

    ofs << "}\n";
    std::cout << "Generated: " << outPath << "\n";
}

// ============================================================
//  GenerateStruct → XxxStruct.g.cs
// ============================================================

void CSharpGenerater::GenerateStruct(const StructInfo& info)
{
    std::string outPath = outputDirectory + "/" + info.name + ".g.cs";
    std::ofstream ofs(outPath);
    if (!ofs.is_open()) throw std::runtime_error("Cannot open: " + outPath);

    ofs << "// <auto-generated/>\n";
    ofs << "using System.Runtime.InteropServices;\n\n";
    ofs << "namespace " << csNamespace << ";\n";
    ofs << "[StructLayout(LayoutKind.Sequential)]\n";
    ofs << "public struct " << info.name << "\n{\n";

    for (const auto& f : info.fields)
    {
        std::string csType = ResolveCsType(f.type);
        std::string marshal = ResolveMarshalAttr(f.type);
        if (!marshal.empty())
            ofs << Indent(1) << "[MarshalAs(" << marshal << ")]\n";
        ofs << Indent(1) << "public " << csType << " " << f.name << ";\n";
    }

    ofs << "}\n";
    std::cout << "Generated: " << outPath << "\n";
}

// ============================================================
//  BuildFieldImportLines
//
//  フィールド1つに対して Get/Set の LibraryImport を出力
//  例:
//    [LibraryImport(Dll)] internal static partial float Rigidbody_GetMass(ulong ownerId);
//    [LibraryImport(Dll)] internal static partial void  Rigidbody_SetMass(ulong ownerId, float value);
// ============================================================

std::string CSharpGenerater::BuildFieldImportLines(
    const std::string& className, const FieldInfo& f, int indent) const
{
    std::string csType = ResolveCsType(f.type);
    std::string marshal = ResolveMarshalAttr(f.type);
    std::string ind = Indent(indent);
    std::string prefix = className + "_";

    // 先頭大文字に変換したフィールド名 (例: mass → Mass)
    std::string capName = f.name;
    if (!capName.empty()) capName[0] = static_cast<char>(std::toupper(capName[0]));

    std::ostringstream oss;

    // Getter
    if (!marshal.empty())
        oss << ind << "[return: MarshalAs(" << marshal << ")]\n";
    oss << ind << "[LibraryImport(Dll)] "
        << "internal static partial " << csType << " "
        << prefix << "Get" << capName << "(ulong ownerId);\n";

    // Setter
    std::string setParam = marshal.empty()
        ? csType + " value"
        : "[MarshalAs(" + marshal + ")] " + csType + " value";
    oss << ind << "[LibraryImport(Dll)] "
        << "internal static partial void "
        << prefix << "Set" << capName << "(ulong ownerId, " << setParam << ");\n";

    return oss.str();
}

// ============================================================
//  BuildLibraryImportLine
//
//  メソッド1つの LibraryImport シグネチャを出力
//  例:
//    [LibraryImport(Dll)] internal static partial void Rigidbody_AddForce(ulong ownerId, Vector3 force, int mode);
// ============================================================

std::string CSharpGenerater::BuildLibraryImportLine(
    const std::string& className, const MethodInfo& m, int indent) const
{
    std::string csRet = ResolveCsType(m.returnType);
    std::string retMarshal = ResolveMarshalAttr(m.returnType);
    std::string ind = Indent(indent);

    std::ostringstream params;
    params << "ulong ownerId";
    for (const auto& [pType, pName] : m.parameters)
    {
        std::string csPType = ResolveCsType(pType);
        std::string pMarshal = ResolveMarshalAttr(pType);
        params << ", ";
        if (!pMarshal.empty())
            params << "[MarshalAs(" << pMarshal << ")] ";
        params << csPType << " " << pName;
    }

    std::ostringstream oss;
    if (!retMarshal.empty())
        oss << ind << "[return: MarshalAs(" << retMarshal << ")]\n";
    oss << ind << "[LibraryImport(Dll)] "
        << "internal static partial " << csRet << " "
        << className << "_" << m.name << "(" << params.str() << ");\n";

    return oss.str();
}

// ============================================================
//  BuildPropertyImpl
//
//  例:
//    public float mass
//    {
//        get => NativeMethods.Rigidbody_GetMass(ownerId);
//        set => NativeMethods.Rigidbody_SetMass(ownerId, value);
//    }
// ============================================================

std::string CSharpGenerater::BuildPropertyImpl(
    const std::string& className, const FieldInfo& f, int indent) const
{
    std::string csType = ResolveCsType(f.type);
    std::string ind = Indent(indent);
    std::string ind2 = Indent(indent + 1);
    std::string nm = nmNamespace + ".NativeMethods";

    // 先頭大文字のフィールド名
    std::string capName = f.name;
    if (!capName.empty()) capName[0] = static_cast<char>(std::toupper(capName[0]));

    // HideInInspector 属性チェック → [System.ComponentModel.EditorBrowsable] を付与
    bool hideInInspector = false;
    for (const auto& attr : f.attributes)
        if (attr.name == "HideInInspector") { hideInInspector = true; break; }

    std::ostringstream oss;
    if (hideInInspector)
        oss << ind << "[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]\n";

    oss << ind << "public " << csType << " " << f.name << "\n";
    oss << ind << "{\n";
    oss << ind2 << "get => " << nm << "." << className << "_Get" << capName << "(ownerId);\n";
    oss << ind2 << "set => " << nm << "." << className << "_Set" << capName << "(ownerId, value);\n";
    oss << ind << "}\n";

    return oss.str();
}

// ============================================================
//  BuildMethodImpl
//
//  例:
//    public void AddForce(Vector3 force, ForceMode mode = default)
//        => NativeMethods.Rigidbody_AddForce(ownerId, force, (int)mode);
// ============================================================

std::string CSharpGenerater::BuildMethodImpl(
    const std::string& className, const MethodInfo& m, int indent) const
{
    std::string csRet = ResolveCsType(m.returnType);
    std::string ind = Indent(indent);
    std::string nm = nmNamespace + ".NativeMethods";

    // C# シグネチャの引数リスト
    std::ostringstream sigParams;
    std::ostringstream callParams;
    callParams << "ownerId";
    bool first = true;
    for (const auto& [pType, pName] : m.parameters)
    {
        std::string csPType = ResolveCsType(pType);
        if (!first) sigParams << ", ";
        sigParams << csPType << " " << pName;
        first = false;

        // enum 型は int にキャストして渡す
        auto it = typeMap.find(pType);
        bool isEnum = (it != typeMap.end() && it->second.source == TypeSource::Generate);
        callParams << ", ";
        if (isEnum) callParams << "(int)";
        callParams << pName;
    }

    std::ostringstream oss;
    oss << ind << "public " << csRet << " " << m.name << "(" << sigParams.str() << ")\n";
    oss << ind << Indent(1);
    if (csRet != "void")
        oss << "=> " << nm << "." << className << "_" << m.name << "(" << callParams.str() << ");\n";
    else
        oss << "=> " << nm << "." << className << "_" << m.name << "(" << callParams.str() << ");\n";

    return oss.str();
}